### ISSUE TITLE
To-Do/Note Edit Mode

### ISSUE THREAD

**Issue by calvinckho** [calvinckho/restvo-app#26]
It is located in showfeature.page.html

- [x] implement the DELETE button on the top as an icon

- [x] Remove the border

- [x] As user is typing on the Note section (collaborative text box), have an indicator at the top of the text box that gives the state: none, "saving...", "saved". Refer to Google doc on how they do it.

Desktop

- [x] Remove the text box border and make the note feature take up entire desktop space

Maybe?

- [x] Either show SAVE button or Show "Saving..." and "Saved" in editor as soon as possible

- [x] Remove the automatic indenting feature

- [ ] From Chat make the entry point into the Relationship/Mentoring Page more obvious. Considering creating a Button/Icon.

- [x] Need Word Editor features: underline, bold, italicize, change font size, bullet points, numbered list is the MINIMUM.

- [ ] Create an update/notification strategy for notes, to-dos, news, etc... Something similar to Chat either we need a Notification Page or find a way to put into Me Page.?

- [ ] Comment/feedback feature for notes? Consider something similar to Google docs?

**Comment by calvinckho** [comment]
@alvinwklee you can post your Figma file here. I'll assign a software eng intern to tackle your design.

**Comment by calvinckho** [comment]
@alexandertsung I moved your improvement suggestions to here.

**Comment by calvinckho** [comment]
@calixo888 I am assigning you this new issue. Can you give it a shot? This is when you are in the relationship page, and click on a To-Do and it opens the Edit To-Do view. Can you try make these improvements?

**Comment by alvinwklee** [comment]
> @alvinwklee you can post your Figma file here. I'll assign a software eng intern to tackle your design.

https://www.figma.com/file/tCYsSppbXBa22E8dE3Tdn4/Restvo-PSWC?node-id=455%3A310

A few of the screens within the flow are a bit outdated (Creating a Goal), but the Create a To-Do screens are good. You can ignore the flow below Create a To-Do since those were just explorations.

**Comment by calvinckho** [comment]
@alvinwklee if you can clean up the figma file a bit and move the outdated or exploration stuff to a different labeled section or page, that will be really helpful. I know @calixo888 was confused last time when he tries to implement the Me page.

**Comment by calixo888** [comment]
Will do, I will try to implement these designs

**Comment by calvinckho** [comment]
@calixo888 wiki definitions:

On To-Do:
https://github.com/calvinckho/restvo-app/wiki/Core-Concepts#to-dos

Content Calendar Item definition here: https://github.com/calvinckho/restvo-app/wiki/Core-Concepts#content-calendar

**Comment by calvinckho** [comment]
showfeature.page.html 
line 155 Content Calendar Item
line 644 Add a Note section - Text answer component

**Comment by calvinckho** [comment]
@alvinwklee Calix is trying to add the 'saving.../saved' state on the Edit To-Do page per our previous discussion. I think Devon has created a version before. Can you add it to the Edit To-Do figma so Calix can implement it? Thanks.

**Comment by alvinwklee** [comment]
> @alvinwklee Calix is trying to add the 'saving.../saved' state on the Edit To-Do page per our previous discussion. I think Devon has created a version before. Can you add it to the Edit To-Do figma so Calix can implement it? Thanks.

 I've put the two screens that show the states within the to-do page and have labeled them. Hope this helps.

**Comment by calvinckho** [comment]
@alvinwklee thanks for adding the 'saved 13 minutes ago'. If we show the exact amount of elapsed time, we would need to refresh it every minute which is more complicated than what Alex and I anticipated. Can we just do 'saving...' and 'saved' and after say 5 sec the label just go away?

**Comment by calvinckho** [comment]
@calixo888 please follow through with Alvin's figma file to finish up the implementation of the other tasks

**Comment by calvinckho** [comment]
@alvinwklee can you create a sketch of what it looks like when a To-Do is assigned to multiple Goals? This is what Calix has so far:
![Screen Shot 2020-06-16 at 2 30 25 PM](https://user-images.githubusercontent.com/23274587/84830231-edc58700-afdd-11ea-8e6e-252f39bdde09.png)

**Comment by calvinckho** [comment]
@calixo888 can you also add the color-code to the Goals? 

in showfeature.page.html line 222, goal[3] has the color code e.g. #cec2ff. 

on implementing the color in html, you can do something like this.
`[ngStyle]="{'background': (goal[3] }"'

**Comment by calvinckho** [comment]
@alvinwklee can you add a case when there are multiple goals selected? Calix needs it to implement for those scenarios. Thanks.

**Comment by alvinwklee** [comment]
> @alvinwklee can you add a case when there are multiple goals selected? Calix needs it to implement for those scenarios. Thanks.

https://www.figma.com/file/tCYsSppbXBa22E8dE3Tdn4/Restvo-PSWC?node-id=455%3A482

**Comment by calvinckho** [comment]
awesome. thanks @alvinwklee. @calixo888 please follow Alvin's design to add the multiple Goal tags.

**Comment by calixo888** [comment]
alright, I'll get on that

**Comment by calvinckho** [comment]
@calixo888 is this done?
